 *** Starting program ungrib.exe ***
Start_date =  2033-12-24_00:00:00 ,      End_date = 2033-12-24_00:00:00
output format is WPS
Path to intermediate files is ./

###############################################################################

Inventory for date = 2033-12-24 00:00:00

PRES   TT       UU       VV       SPECHUMD RH       LANDSEA  SOILHGT  SEAICE   SNOW     PSFC     PMSL     SKINTEMP SST      ST000007 ST007028 ST028100 ST100289 SM000007 SM007028 SM028100 SM100289
-------------------------------------------------------------------------------
2001.0  O        O        O        O        O        O        X        O        O        O        O        O        O        O        O        O        O        O        O        O        O      
-------------------------------------------------------------------------------

###############################################################################

Inventory for date = 2033-12-24 00:00:00

PRES   TT       UU       VV       SPECHUMD RH       LANDSEA  SOILHGT  SEAICE   SNOW     PSFC     PMSL     SKINTEMP SST      ST000007 ST007028 ST028100 ST100289 SM000007 SM007028 SM028100 SM100289
-------------------------------------------------------------------------------
2001.0  O        O        O        O        O        X        O        O        O        O        O        O        O        O        O        O        O        O        O        O        O      
-------------------------------------------------------------------------------
 Name of source model =>unknown model and orig center   

###############################################################################

Inventory for date = 2033-12-24 00:00:00

PRES   TT       UU       VV       SPECHUMD RH       LANDSEA  SOILHGT  SEAICE   SNOW     PSFC     PMSL     SKINTEMP SST      ST000007 ST007028 ST028100 ST100289 SM000007 SM007028 SM028100 SM100289
-------------------------------------------------------------------------------
2001.0  O        O        O        O        O        X        X        O        O        O        O        O        O        O        O        O        O        O        O        O        O      
-------------------------------------------------------------------------------
Subroutine DATINT: Interpolating 3-d files to fill in any missing data...
Looking for data at time 2033-12-24_00
Found file:      FX:2033-12-24_00
End Subroutine DATINT.

**********
Deleting temporary files created by ungrib...
**********

Deleting file:  ./PFILE:2033-12-24_00

**********
Done deleting temporary files.
**********

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!  Successful completion of ungrib.   !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
